// modominator-react-example/src/App.js
import React from "react";

import "./App.css";

class App extends React.Component {
  constructor(props) {
    super(props);

    let defaultImg = "";
    this.state = { value: defaultImg };
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(event) {
    this.setState({ value: event.target.value });
  }

  render() {
    return (
      <div className="App">
        <h1>Show your favorite image</h1>
        <input
          placeholder="Paste your favorite image URL, like https://placeimg.com/320/320/any"
          value={this.state.value}
          onChange={this.handleChange}
        />
        <div
          dangerouslySetInnerHTML={{
            __html: `<img src="${this.state.value}"/>`
          }}
        />
      </div>
    );
  }
}

export default App;

// modominator-vue-example/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <h1>Show your favorite image</h1>
    <input
      placeholder="Paste your favorite image URL, like https://placeimg.com/320/320/any"
      v-model="url"
    />
    <div v-html="image"></div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  name: 'app',
  data() {
    return {
      url: ''
    };
  },
  computed: {
    image(): string {
      return this.url ? `<img src="${this.url}"/>` : '';
    }
  }
});
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
